FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime


# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-opencv \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Install Python dependencies
RUN pip install --no-cache-dir \
    opencv-python \
    pyyaml \
    matplotlib
